✨ add Week8
LouisaStrunk02/CS50Kurs pull request #13
Opened 2022-09-02 07:22 UTC by LouisaStrunk02

Changes:

1. add index.html
2. add EMWinner.html
3. add WMWinner.html
4. add Player.html
5. add styles.css

2022-09-02 07:58 UTC, stefanluth commented on week8/trivia/index.html
> +</html>
EOF

2022-09-02 07:58 UTC, stefanluth commented on week8/trivia/styles.css
> +}
EOF

2022-09-02 08:36 UTC, DevBastiS requested changes

2022-09-02 08:36 UTC, DevBastiS commented on week8/homepage/EMWinner.html
> +<head>
<head> Tag should be indeted.

HTML in general should have an indent of 2 spaces, plese check your editor configuration.

2022-09-02 08:36 UTC, DevBastiS commented on week8/homepage/EMWinner.html
> +    <title>Homepage/example - Louisa </title>
```suggestion
    <title>Homepage/example - Louisa</title>
```

2022-09-02 08:36 UTC, DevBastiS commented on week8/homepage/index.html
> +         });
Move this script into a javascript file please.

2022-09-02 08:36 UTC, DevBastiS commented on week8/homepage/styles.css
> +    background-color: #11bfc896;
CSS should have an indent of 2 spaces as well.

2022-09-02 08:36 UTC, DevBastiS commented on week8/trivia/index.html
> +        });
Move to script file please.

2022-09-02 08:36 UTC, DevBastiS commented on week8/homepage/Player.html
> +        <table id="Player" class="table table-hover">
table-hover is not used in your css files.

2022-09-06 06:19 UTC, LouisaStrunk02 commented on week8/homepage/Player.html
> +        <table id="Player" class="table table-hover">
table-hover is a feature from Bootstrap: https://getbootstrap.com/docs/4.0/content/tables/

2022-09-06 06:50 UTC, stefanluth approved these changes
You could limit the name field to [a-zA-Z] but then again there are people like [Elon Musk](https://www.google.com/search?q=X+%C3%86+A-12+Musk). So I guess your version is future proof.

![Screenshot 2022-09-06 at 08 47 47](https://user-images.githubusercontent.com/80166473/188565699-cc593c65-c357-4586-857f-422a035f3c16.png)

2022-09-06 06:50 UTC, stefanluth commented on week8/homepage/Player.html
> +          </tr>
I feel like there's one very famous and successful German player missing. :D

2022-09-06 13:43 UTC, stefanluth commented
:D

2022-09-06 14:14 UTC, DevBastiS approved these changes

2022-09-07 12:14 UTC, stefanluth approved these changes

2022-09-07 12:20 UTC, merged