✨Add week1 (change format and add cash and credit)
LouisaStrunk02/CS50Kurs pull request #3
Opened 2022-08-05 07:57 UTC by LouisaStrunk02

2022-08-05 08:35 UTC, DevBastiS requested changes

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    // TODO
What is TODO here? Remove the comment ;)

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    int cents;
```suggestion
    int cents;
    
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    } while (cents < 0);
```suggestion
    } while (cents < 0);
    
```

Rule of thumb: Always place a new line before a return statement to increase readability.

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    // TODO
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    quarters = cents / 25;
```suggestion
    quarters = cents / 25;
    
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    // TODO
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    dimes = cents / 10;
```suggestion
    dimes = cents / 10;
    
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    // TODO
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    nickels = cents / 5;
```suggestion
    nickels = cents / 5;
    
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    // TODO
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +    pennies = cents / 1;
```suggestion
    pennies = cents / 1;
    
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/cash/cash.c
> +int calculate_pennies(int cents)
Is this method necessary? It returns the value you give into it.

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +    long cnumber = get_long("Number: ");
What dies "cnumber" mean? Please try to find a better name for all variables here.
For example "a" is not a good name for a variable since it doesn't state what this variable is for.
"CountingSomething" may be a better name.

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +    bool even = false;
Another good example: What is "even" here?

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +        r = a % 10;
```suggestion
        r = a % 10;
        
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +            n = r * 2;
```suggestion
            n = r * 2;
            
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +        }
```suggestion
        }
        
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +            int atest = cnumber / pow(10, 13);
```suggestion
            int atest = cnumber / pow(10, 13);
            
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/credit/credit.c
> +            int vtest = cnumber / pow(10, 15);
```suggestion
            int vtest = cnumber / pow(10, 15);
            
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/hello/hello.c
> +}
```suggestion
}

```

Always add a new line at the end of the file.

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +    // for each row
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +        // for each column
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +            // print nothing
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +            // print a brick
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +        // move to next row
```suggestion
```

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +        // move to next row
Rule of thumb: Don't use comments, like never.
If the code needs comments to be readable the code isn't written well enough.

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-less/mario.c
> +}
```suggestion
}

```

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-more/mario.c
> +    // for each row
Remove all comments in this file.

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-more/mario.c
> +            // print nothing
This comment for example just states the obvious "The next line prints a space"

2022-08-05 08:35 UTC, DevBastiS commented on week1/mario-more/mario.c
> +}
```suggestion
}

```

2022-08-05 12:42 UTC, DevBastiS approved these changes
LGTM now. Please wait for @shoreal approve :)

2022-08-08 08:40 UTC, shoreal approved these changes

2022-08-08 09:26 UTC, merged