add week2
LouisaStrunk02/CS50Kurs pull request #4
Opened 2022-08-10 15:12 UTC by LouisaStrunk02

Changes:
1. add scrabble
2. add readability
3. add caesar
4. add substitution

2022-08-10 15:39 UTC, DevBastiS approved these changes

2022-08-10 15:39 UTC, DevBastiS commented on week2/caesar/caesar.c
> +// char rotate(char text[], int k)
Remove unused Codes.

2022-08-11 06:38 UTC, MKrips requested changes
Just some readability changes. Dont forget that the cs50-library has some neat functions that help make your code more readable.

2022-08-11 06:38 UTC, MKrips commented on week2/readability/readability.c
> +        }
```suggestion

```
This code has no real function, so you dont need it.

2022-08-11 06:38 UTC, MKrips commented on week2/readability/readability.c
> +        }
```suggestion

```
Same as above

2022-08-11 06:38 UTC, MKrips commented on week2/readability/readability.c
> +        if (text[i] >= 'A' && text[i] <= 'Z' || text[i] >= 'a' && text[i] <= 'z')
As far as I am aware, the library you use has an isalpha-function that checks whether you have a letter. That function would be better here for readability purposes.

2022-08-11 06:38 UTC, MKrips commented on week2/substitution/substitution.c
> +            key[i] = key[i] - 32;
```suggestion
            key[i] = toupper(key[i]);
```
This is more readable, provided you want everything uppercase.

2022-08-12 06:28 UTC, MKrips approved these changes

2022-08-12 06:36 UTC, merged