add Week3
LouisaStrunk02/CS50Kurs pull request #5
Opened 2022-08-12 11:40 UTC by LouisaStrunk02

Changes:
1. add plurability
2. add runoff
3. add tideman

2022-08-15 06:26 UTC, DevBastiS approved these changes
LGTM

2022-08-15 11:39 UTC, shoreal requested changes

2022-08-15 11:39 UTC, shoreal commented on week3/runoff/runoff.c
> +            if (!vote(i, j, name))
Here I guess a speaking variable would make it easier to understand.

2022-08-15 11:39 UTC, shoreal commented on week3/runoff/runoff.c
> +        if (strcmp(candidates[i].name, name) == 0)
```suggestion
        bool candidateIsCandidateToVote = strcmp(candidates[i].name, name) == 0;
        if (candidateIsCandidateToVote)
```

Same as above, I guess it is something like `candidateIsCandidateToVote`, or? But I am not sure, thats why I suggest to use a speaking variable here, too. Also I am not sure about defining a variable in C, so don't use my code-suggestion without testing it. Could be possible that this will not work :D

2022-08-15 11:39 UTC, shoreal commented on week3/tideman/tideman.c
> +            if (preferences[pairs[i].winner][pairs[i].loser] < preferences[pairs[j].winner][pairs[j].loser])
Same as above, here I can't understand what the condition is.

2022-08-16 07:26 UTC, shoreal approved these changes

2022-08-16 07:32 UTC, merged