Week4
LouisaStrunk02/CS50Kurs pull request #9
Opened 2022-08-19 11:52 UTC by LouisaStrunk02

2022-08-23 12:36 UTC, stefanluth requested changes
My review comments in `filter-less/filter.c` also apply to the other files.

2022-08-23 12:36 UTC, stefanluth commented on week4/filter-less/filter.c
> +
`inptr` is not used afterwards, you might want to close the file here.

2022-08-23 12:36 UTC, stefanluth commented on week4/filter-less/filter.c
> +    FILE *outptr = fopen(outfile, "w");
`outptr` is not needed until you actually write to the file further down (line  125+). You might want to move this to right before writing happens. That way you don't need to close the file in every if-check.

2022-08-23 12:36 UTC, stefanluth commented on week4/filter-less/filter.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Is this file needed?

2022-08-23 12:36 UTC, stefanluth commented on week4/recover/recover.c
> +        bool isStartOfJPEG = (buffer[0] == 0xff && buffer[1] == 0xd8 && buffer[2] == 0xff && (buffer[3] & 0xf0) == 0xe0);
Keep variables consistent. (snake_case)

2022-08-24 06:36 UTC, stefanluth requested changes
Resolved unresolved requested changes without comments.

2022-08-24 06:37 UTC, stefanluth commented on week4/filter-less/helpers.c
> +                    bool pixel_Nonexistent = currentX < 0 || currentX >= height || currentY < 0 || currentY >= width;
```suggestion
                    bool pixel_nonexistent = currentX < 0 || currentX >= height || currentY < 0 || currentY >= width;
```

2022-08-24 06:38 UTC, stefanluth commented on week4/recover/recover.c
> +        bool is_Start_Of_JPEG = (buffer[0] == 0xff && buffer[1] == 0xd8 && buffer[2] == 0xff && (buffer[3] & 0xf0) == 0xe0);
```suggestion
        bool is_start_of_jpeg = (buffer[0] == 0xff && buffer[1] == 0xd8 && buffer[2] == 0xff && (buffer[3] & 0xf0) == 0xe0);
```

2022-08-24 06:39 UTC, stefanluth commented on week4/filter-less/helpers.c
> +                    bool pixel_Nonexistent = currentX < 0 || currentX >= height || currentY < 0 || currentY >= width;
[snake_case](https://en.wikipedia.org/wiki/Snake_case) starts each word with lowercase letters

2022-08-24 06:47 UTC, stefanluth commented on week4/filter-less/filter.c
> +    FILE *outptr = fopen(outfile, "w");
Resolved as file was given by task and not edited.

2022-08-24 06:49 UTC, stefanluth commented on week4/filter-less/helpers.c
> +                    bool pixel_Nonexistent = currentX < 0 || currentX >= height || currentY < 0 || currentY >= width;
Nvm, you use [camelCase](https://en.wikipedia.org/wiki/Camel_case) everywhere else, so use that.

2022-08-24 06:49 UTC, stefanluth commented on week4/filter-less/helpers.c
> +                    bool pixel_Nonexistent = currentX < 0 || currentX >= height || currentY < 0 || currentY >= width;
```suggestion
                    bool pixelNonExistent = currentX < 0 || currentX >= height || currentY < 0 || currentY >= width;
```

2022-08-24 06:50 UTC, stefanluth commented on week4/filter-more/helpers.c
> +                    if (pixel_Nonexistent)
```suggestion
                    bool pixelNonExistent = ...
```

2022-08-24 06:51 UTC, stefanluth commented on week4/filter-more/helpers.c
> +                    if (pixel_Nonexistent)
Sorry, use [camelCase](https://en.wikipedia.org/wiki/Camel_case) as done above and elsewhere.

2022-08-24 06:51 UTC, stefanluth commented on week4/filter-more/helpers.c
> +            float pixelcounter = 0.00;
```suggestion
            float pixelCounter = 0.00;
```

2022-08-24 06:52 UTC, LouisaStrunk02 commented on week4/filter-less/filter.c
> +
In filter-more and filter-less I only had to create helpers.c myself. The other files were given by the task.

2022-08-24 07:06 UTC, LouisaStrunk02 commented on week4/filter-less/filter.c
> +    FILE *outptr = fopen(outfile, "w");
same as above

2022-08-24 07:07 UTC, LouisaStrunk02 commented on week4/filter-less/filter.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
same as above

2022-08-24 07:11 UTC, stefanluth commented on week4/filter-more/helpers.c
> +            int red = round(sqrt((redX * redX) + (redY * redY)));
```suggestion
            }

            int red = round(sqrt((redX * redX) + (redY * redY)));
```

2022-08-24 07:47 UTC, stefanluth requested changes
Could you add a blank line before each function's last return?

2022-08-24 07:47 UTC, stefanluth commented on week4/volume/volume.c
> +    fclose(output);
Missing return.

2022-08-24 07:47 UTC, stefanluth reviewed
Examples

2022-08-24 07:47 UTC, stefanluth commented on week4/filter-less/helpers.c
> +    return;
Blank line here
```suggestion
    }

    return;
```

2022-08-24 07:47 UTC, stefanluth commented on week4/filter-less/helpers.c
> +    return;
```suggestion
    }

    return;
```

2022-08-24 07:47 UTC, stefanluth commented on week4/filter-less/helpers.c
> +    return;
```suggestion
    }

    return;
```

2022-08-24 11:27 UTC, LouisaStrunk02 commented on week4/volume/volume.c
> +    fclose(output);
A return statement results in an error message.

2022-08-24 14:59 UTC, stefanluth approved these changes

2022-08-24 15:15 UTC, shoreal requested changes
Delete the .DS_Store files. Code LGTM

2022-08-25 06:26 UTC, DevBastiS approved these changes
Code LGTM, do what @shoreal said, after that it is fine.

2022-08-25 06:54 UTC, stefanluth commented
> Delete the .DS_Store files. Code LGTM

Add a `.gitignore` [file](https://www.atlassian.com/de/git/tutorials/saving-changes/gitignore) and include `.DS_Store` 👍

2022-08-25 08:39 UTC, shoreal requested changes

2022-08-25 08:39 UTC, shoreal commented on .gitignore
> +**/.DS_Store
EOF missing 🙈😅

2022-08-25 10:50 UTC, merged